import os

MODEL_PATH = ""
DATASET_PATH = r"C:\Users\jatvi\OneDrive\Desktop\5th Sem\SE\SE PROJECT\GTZAN\genres_original"
FEATURE_PATH = "mfcc.json"
MAPPING_PATH = "mapping.json"

SAMPLE_RATE = 22050
TRACK_DURATION_SECONDS = 30
NUM_SEGMENTS = 10
SAMPLES_PER_TRACK = SAMPLE_RATE * TRACK_DURATION_SECONDS